eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,
                   http://localhost:8762/eureka
spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
   sampler:
    probability: 1 #100% (default = 10%)
  data:
    mongodb:
      uri: mongodb://localhost:27017/BookQuery
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gid
      auto-offset-reset: earliest
      
