eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,
                   http://localhost:8762/eureka
spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
   sampler:
    probability: 1 #100% (default = 10%)
  data:
    mongodb:
      uri: mongodb://localhost:27017/Borrowing
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: gid
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.miu.service.dto
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
